---
version: "2.3"
services:
  sut:
    image: appropriate/curl
    command: "-sSf http://broker:8082/status"
    depends_on:
      broker:
        condition: service_healthy

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: 'echo ruok | nc localhost 2181 | grep imok'
      interval: 5s
      timeout: 5s
      retries: 12

  overlord:
    container_name: overlord
    build: .
    ports:
      - "8090:8090"
    command:
      - overlord
    depends_on:
      zookeeper:
        condition: service_healthy
      postgres:
        condition: service_started

  coordinator:
    container_name: coordinator
    build: .
    ports:
      - "8081:8081"
    command:
      - coordinator
    depends_on:
      zookeeper:
        condition: service_healthy
      postgres:
        condition: service_started

  middlemanager:
    container_name: middlemanager
    build: .
    ports:
      - "8091:8091"
    command:
      - middleManager
    depends_on:
      zookeeper:
        condition: service_healthy
      postgres:
        condition: service_started

  historical:
    container_name: historical
    build: .
    ports:
      - "8093:8093"
    command:
      - historical
    depends_on:
      zookeeper:
        condition: service_healthy
      postgres:
        condition: service_started

  broker:
    container_name: broker
    build: .
    ports:
      - "8082:8082"
    command:
      - broker
    depends_on:
      zookeeper:
        condition: service_healthy
      postgres:
        condition: service_started
    healthcheck:
      test: 'echo -e "GET http://localhost:8082/status HTTP/1.1\r\nHost: localhost\r\n\r\n" | nc localhost 8082 | grep io.druid'
      interval: 5s
      timeout: 5s
      retries: 12
