version: "2"
services:

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

  zookeeper:
    container_name: zookeeper
    restart: always
    image: znly/zookeeper:3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper

  overlord:
    container_name: overlord
    restart: always
    image: rusnyder/druid:latest
    ports:
      - 8090:8090
    environment:
      - JAVA_EXTRA_OPTIONS=-Xmx1g -Xms1m
    links:
      - zookeeper:zookeeper
      - postgres:postgres
    command:
      - overlord

  coordinator:
    container_name: coordinator
    restart: always
    image: rusnyder/druid:latest
    ports:
      - 8081:8081
    links:
      - zookeeper:zookeeper
      - postgres:postgres
    command:
      - coordinator

  middlemanager:
    container_name: middlemanager
    restart: always
    image: rusnyder/druid:latest
    ports:
      - 8091:8091
      - 8100-8199:8100-8199
    environment:
      - JAVA_EXTRA_OPTIONS=-Xmx64m -Xms64m
    links:
      - zookeeper:zookeeper
      - postgres:postgres
    command:
      - middleManager

  historical:
    container_name: historical
    restart: always
    image: rusnyder/druid:latest
    ports:
      - 8093:8093
    links:
      - zookeeper:zookeeper
      - postgres:postgres
    command:
      - historical

  broker:
    container_name: broker
    restart: always
    image: rusnyder/druid:latest
    ports:
      - 8082:8082
    links:
      - zookeeper:zookeeper
      - postgres:postgres
    command:
      - broker

  tranquility:
    container_name: tranquility
    image: rusnyder/tranquility:latest
    ports:
      - 8200:8200
    volumes:
      - ./conf/tranquility:/etc/tranquility
    environment:
      TRANQUILITY_CONFIG_FILE: /etc/tranquility/config.json
      TRANQUILITY_PROPERTIES_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper:zookeeper
      - broker:broker
      - coordinator:coordinator
      - historical:historical
      - middlemanager:middlemanager
      - overlord:overlord

  superset:
    container_name: superset
    restart: always
    image: amancevice/superset
    environment:
      - PYTHONPAT=$WHEREYOURCONFIGIS:$PYTHONPATH
    ports:
      - 8088:8088
    links:
      - broker:broker
      - coordinator:coordinator
    volumes:
      - ./.superset:/etc/superset

volumes:
  postgres:
    external: true
